# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93c6425d08b389cece6ddb3abe9c97381c4589a626d81341a32c01652423283df8ee7eb22c7723869c3a212fbda6eac7b0a27891e62d042568d82b3f3cd6065f

test:
  secret_key_base: ef79c8de75a81026c962f559e0a9319992b835cea404695b481c3e365a36504a9e9521051cb13f8071e54d334744bc45666848f696c3a300847477d0b539e1e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  google_analytics_code: YOUR CODE HERE
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>